Add replica option for postgres database
hmcts/cnp-module-postgres pull request #99
Opened 2022-09-08 12:16 UTC by thomast1906

### Change description ###
Add replica option for postgres database

Tested on a PoC that database permissions are replicated, example `tamops` / `tamopsnew` roles copied to replicated database
```
exampledb=> \du
                                                  List of roles
            Role name            |                         Attributes                         |    Member of     
---------------------------------+------------------------------------------------------------+------------------
 azure_pg_admin                  | Cannot login, Replication                                  | {}
 azure_replication_user_9d4606f8 | Replication                                                | {}
 azure_superuser                 | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 psqladmin                       | Create role, Create DB, Replication                        | {azure_pg_admin}
 tamops                          | Cannot login                                               | {}
 tamopsnew                       | Cannot login                                               | {}
```
 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-09-08 12:18 UTC, thomast1906 commented
Going to find a team/database to test with. 

have tested this setup similar on my own setup.

2022-09-08 12:52 UTC, timja commented on variables.tf
> +variable "replica_enable" {
I don't think this is needed, just iterate over the replicas list

2022-09-08 12:52 UTC, timja requested changes
documentation needs updating, and I think can be simplified

2022-09-09 08:30 UTC, thomast1906 commented
Yup, will do documentation at the end 

example PR: https://build.platform.hmcts.net/blue/organizations/jenkins/HMCTS_d_to_i%2Fhmc-cft-hearing-service/detail/PR-302/8/pipeline/197

2022-09-09 12:45 UTC, thomast1906 commented on variables.tf
> +  default = []
added

2022-09-09 13:02 UTC, timja approved these changes

2022-09-09 15:41 UTC, merged